
package edu.avanzada.parcial1.vista;

import edu.avanzada.parcial1.control.ControlPrincipal;

/**
 *
 *  @author Ana, Samuel, Juan
 */
public class VentanaActualizar extends javax.swing.JFrame {

    private ControlPrincipal control;
    
    /**
     * Creates new form VentanaRegistrarRaza
     */
    public VentanaActualizar(ControlPrincipal aThis) {
        control = aThis;
        initComponents();
        setLocationRelativeTo(null);
        TextCompletarNombre.setEditable(false);
        TextCompletarPais.setEditable(false);
    }
    
    public void limpiar(){
        TextCompletarApariencia.setText("");
        TextCompletarCola.setText("");
        TextCompletarColor.setText("");
        TextCompletarEspalda.setText("");
        TextCompletarLomo.setText("");
        TextCompletarPecho.setText("");
        TextCompletarPelo.setText("");
        TextCompletarPais.setText("");
        TextCompletarNombre.setText("");
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelDatos = new javax.swing.JPanel();
        TextCompletarApariencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextCompletarEspalda = new javax.swing.JTextField();
        TextCompletarPelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextCompletarCola = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextCompletarColor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextCompletarLomo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextCompletarPecho = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ComboBoxSeccion = new javax.swing.JComboBox<>();
        ComboBoxGrupo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        TextCompletarNombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TextCompletarPais = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 228, 255));
        jPanel1.setLayout(null);

        PanelDatos.setBackground(new java.awt.Color(204, 204, 255));
        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 0, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        TextCompletarApariencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarAparienciaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Apariencia: ");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Pelo:");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Color (Manto):");

        TextCompletarEspalda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarEspaldaActionPerformed(evt);
            }
        });

        TextCompletarPelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarPeloActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Espalda:");

        TextCompletarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarColaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Lomo:");

        TextCompletarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarColorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Cola:");

        TextCompletarLomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarLomoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Pecho:");

        TextCompletarPecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarPechoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel11.setText("Clasificacion");

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Grupo:");

        ComboBoxSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSeccionActionPerformed(evt);
            }
        });

        ComboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupo I: perros de pastor y perros boyeros.", "Grupo II: perros Pinscher, Schnauzer, Molosoide y perros Boyeros Suizos.", "Grupo III: perros Terriers.", "Grupo IV: perros Dachshund o Teckel.", "Grupo V: perros tipo Spitz y tipo primitivo.", "Grupo VI: perros tipo sabueso y perros de rastreo.", "Grupo VII: perros de muestra.", "Grupo VIII: perros cobradores, cazadores y perros de aguas.", "Grupo IX: perros de compañía.", "Grupo X: perros lebreles." }));
        ComboBoxGrupo.setBorder(null);
        ComboBoxGrupo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxGrupoItemStateChanged(evt);
            }
        });
        ComboBoxGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxGrupoMouseClicked(evt);
            }
        });
        ComboBoxGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGrupoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Seccion:");

        TextCompletarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarNombreActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Nombre");

        TextCompletarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCompletarPaisActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Pais");

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextCompletarEspalda)
                                    .addComponent(TextCompletarApariencia))
                                .addGap(46, 46, 46)
                                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(40, 40, 40))
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addComponent(TextCompletarPecho, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextCompletarPelo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(TextCompletarColor)
                            .addComponent(TextCompletarNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(90, 90, 90)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextCompletarLomo, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(TextCompletarCola)
                            .addComponent(TextCompletarPais))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(TextCompletarApariencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextCompletarLomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextCompletarEspalda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelDatosLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(TextCompletarPecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelDatosLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel15))))
                            .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(TextCompletarCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextCompletarPelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(TextCompletarColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextCompletarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCompletarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(ComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(PanelDatos);
        PanelDatos.setBounds(12, 37, 984, 198);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Completar Razas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(438, 6, 165, 25);

        BotonActualizar.setBackground(new java.awt.Color(204, 204, 255));
        BotonActualizar.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        BotonActualizar.setText("Actualizar");
        BotonActualizar.setBorder(null);
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonActualizar);
        BotonActualizar.setBounds(830, 358, 155, 32);

        jLabel3.setText("las razas para continuar)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(670, 370, 136, 16);

        jLabel14.setText("(Debe completar todas ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(665, 358, 129, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCompletarAparienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarAparienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarAparienciaActionPerformed

    private void TextCompletarEspaldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarEspaldaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarEspaldaActionPerformed

    private void TextCompletarPeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarPeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarPeloActionPerformed

    private void TextCompletarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarColaActionPerformed

    private void TextCompletarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarColorActionPerformed

    private void TextCompletarLomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarLomoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarLomoActionPerformed

    private void TextCompletarPechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarPechoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarPechoActionPerformed

    private void ComboBoxGrupoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxGrupoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxGrupoItemStateChanged

    private void ComboBoxGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxGrupoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBoxGrupoMouseClicked

    private void ComboBoxGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGrupoActionPerformed

    

    String grupoSeleccionado = (String) ComboBoxGrupo.getSelectedItem(); 
    
    ComboBoxSeccion.removeAllItems();
    ComboBoxSeccion.setSelectedItem(null);

    // Si hay un valor seleccionado, proceder con el switch
    if (grupoSeleccionado != null) {
        switch (grupoSeleccionado) {
            case "Grupo I: perros de pastor y perros boyeros.":
                ComboBoxSeccion.addItem("Sección 1: Perros de pastor");
                ComboBoxSeccion.addItem("Sección 2: Perros boyeros");
                break;
            case "Grupo II: perros Pinscher, Schnauzer, Molosoide y perros Boyeros Suizos.":
                ComboBoxSeccion.addItem("Sección 1: Perros Pinscher y Schanuzer");
                ComboBoxSeccion.addItem("Sección 2: Perros Molosoides");
                ComboBoxSeccion.addItem("Sección 3: Perros tipo montaña y boyeros suizos");
                break;
            case "Grupo III: perros Terriers.":
                ComboBoxSeccion.addItem("Sección 1: Terriers de talla grande y media");
                ComboBoxSeccion.addItem("Sección 2: Terriers de talla pequeña");
                ComboBoxSeccion.addItem("Sección 3: Terriers tipo bull");
                ComboBoxSeccion.addItem("Sección 4: Terriers de compañía");
                break;
            case "Grupo IV: perros Dachshund o Teckel.":
                // No hay secciones para este grupo
                break;
            case "Grupo V: perros tipo Spitz y tipo primitivo.":
                ComboBoxSeccion.addItem("Sección 1: Perros nórdico de trineo");
                ComboBoxSeccion.addItem("Sección 2: Perros nórdicos de cacería");
                ComboBoxSeccion.addItem("Sección 3: Perros nórdicos de guarda y pastoreo");
                ComboBoxSeccion.addItem("Sección 4: Spitz europeos");
                ComboBoxSeccion.addItem("Sección 5: Spitz asiáticos y razas semejantes");
                ComboBoxSeccion.addItem("Sección 6: Tipo primitivo");
                ComboBoxSeccion.addItem("Sección 7: Tipo primitivo - perros de caza");
                break;
            case "Grupo VI: perros tipo sabueso y perros de rastreo.":
                ComboBoxSeccion.addItem("Sección 1: Perros tipo sabueso");
                ComboBoxSeccion.addItem("Sección 2: Perros de rastro");
                ComboBoxSeccion.addItem("Sección 3: Razas semejantes");
                break;
            case "Grupo VII: perros de muestra.":
                ComboBoxSeccion.addItem("Sección 1: Perros de muestra continentales");
                ComboBoxSeccion.addItem("Sección 2: Perros de muestra ingleses e irlandeses");
                break;
            case "Grupo VIII: perros cobradores, cazadores y perros de aguas.":
                ComboBoxSeccion.addItem("Sección 1: Perros cobradores de caza");
                ComboBoxSeccion.addItem("Sección 2: Perros levantadores de caza");
                ComboBoxSeccion.addItem("Sección 3: Perros de agua.");
                break;
            case "Grupo IX: perros de compañía.":
                ComboBoxSeccion.addItem("Sección 1: Bichons y razas semejantes");
                ComboBoxSeccion.addItem("Sección 2: Caniche");
                ComboBoxSeccion.addItem("Sección 3: Perros belga de talla pequeña");
                ComboBoxSeccion.addItem("Sección 4: Perros sin pelos");
                ComboBoxSeccion.addItem("Sección 5: Perros tibetanos");
                ComboBoxSeccion.addItem("Sección 6: Chihuahueno");
                ComboBoxSeccion.addItem("Sección 7: Spaniels ingleses de compañía");
                ComboBoxSeccion.addItem("Sección 8: Spaniels japoneses y pekineses");
                ComboBoxSeccion.addItem("Sección 9: Spaniels continental enano y otro");
                ComboBoxSeccion.addItem("Sección 10: Kromfohrlande");
                ComboBoxSeccion.addItem("Sección 11: Molosoides de talla pequeña");
                break;
            case "Grupo X: perros lebreles.":
                ComboBoxSeccion.addItem("Sección 1: lebreles de pelo largo u ondulado");
                ComboBoxSeccion.addItem("Sección 2: lebreles de pelo duro");
                ComboBoxSeccion.addItem("Sección 3: lebreles de pelo corto");
                break;
        }
    }

    

    }//GEN-LAST:event_ComboBoxGrupoActionPerformed

    private void ComboBoxSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxSeccionActionPerformed
        
    }//GEN-LAST:event_ComboBoxSeccionActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void TextCompletarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarNombreActionPerformed

    private void TextCompletarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCompletarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCompletarPaisActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonActualizar;
    public javax.swing.JComboBox<String> ComboBoxGrupo;
    public javax.swing.JComboBox<String> ComboBoxSeccion;
    private javax.swing.JPanel PanelDatos;
    public javax.swing.JTextField TextCompletarApariencia;
    public javax.swing.JTextField TextCompletarCola;
    public javax.swing.JTextField TextCompletarColor;
    public javax.swing.JTextField TextCompletarEspalda;
    public javax.swing.JTextField TextCompletarLomo;
    public javax.swing.JTextField TextCompletarNombre;
    public javax.swing.JTextField TextCompletarPais;
    public javax.swing.JTextField TextCompletarPecho;
    public javax.swing.JTextField TextCompletarPelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
